### PR TITLE
added Advisors section & minor link changes

### PR DESCRIPTION
**Pull request by jahway603**
added Advisors section & minor link changes

### CODE REVIEW

**Comment by gilardh** [comment]
1) For me the AtomicDEX link is not broken :
image
but it is actually better to refer to the page: https://atomicdex.io/ because it has the links to download the iOS and Android version :
image

2) The JL777 logo is nicer but I don't understand the purpose of this new presentation.
image

3) It is a very good idea to change bottom navigation to use redirects.

**Comment by gilardh** [comment]
4) The text is wrong and the gray frame is not big enough:
image

**Comment by leto** [comment]
@gilardh I asked to have jl777 moved to an "Advisors" section since we are going to add more advisors, and technically jl777 has never been in the Hush core team, but always as been a mentor/advisor. Looks like we need to update that section to say "Advisors". I do like the new jl777 graphic that he uses in other places.

AtomicDEX was recently named to AtomicDeFi so I wouldn't worry to much about links/etc to that, everything is changing, again.

@gilardh since you are going to the FRENCH Google Play Store, it could be that things work for you, but not for the English language store. As I said, everything is changing with AtomicDEX name, and maybe they started that process on the EN store but not the FR store. It gets very complicated with how you release Andoird apps to each "language version" of the app store

**Comment by leto** [comment]
@jahway603 thanks for working on this

**Comment by gilardh** [comment]
Then we can accept the commit of @jahway603 .
It will be necessary (@jahway603 or me) to make some small corrections soon after.
Tell me if you want me to take care of it.

**Comment by leto** [comment]
@gilardh yes plz make your magic updates!!!

**Pull request merged**
